// Conteúdo do cardápio — transcrito do "Cardápio Brew 2026".
// É AQUI que se mexe em item, descrição e preço. Mídia (foto/vídeo) é ligada
// pelo `id`: media/fotos/<id>.webp e media/videos/<id>.mp4 (ver ferramentas/).
//
// Item: { id, nome, desc?, preco? | precos?: [{ rotulo, valor }], nota?, sabores?, midia?, detalhes? }
//   midia   -> usa a mídia de outro id (ex.: a picanha "para 2" reaproveita a da picanha)
//   nota    -> etiqueta curta ao lado do nome ("Para 2 pessoas", "4 unidades")
// Grupo: { nome?, nota?, precos?, itens }  — subdivisão dentro da categoria.

export const restaurante = {
  nome: 'Brew Bar·B·Q Pub',
  cidade: 'Nova Friburgo',
  instagram: 'brewbarbq',
  instagramUrl: 'https://www.instagram.com/brewbarbq',
  slogan: 'Beer · Gin · Steak · Wine',
  boasVindas:
    'No coração de Nova Friburgo, o destino dos amantes de carnes nobres e sabores autênticos.',
};

// "Best BBQ" — a página de destaque do cardápio impresso.
export const destaques = {
  titulo: 'Best BBQ',
  itens: ['steak-and-shrimp', 'prime-rib-angus', 'ny-stripe-black-angus'],
};

export const categorias = [
  {
    id: 'brew-classics',
    nome: 'Brew Classics',
    grupos: [{
      itens: [
        { id: 'salmao-ao-brie-e-shitake', nome: 'Salmão ao Brie e Shitake',
          desc: 'Salmão ao molho de brie, shitake, tomate confit e batata com queijo emmental', preco: 84 },
        { id: 'gods-shrimp', nome: 'Gods Shrimp',
          desc: 'Camarão com arroz cremoso com bacon, creme de milho e batata palha artesanal', preco: 89 },
        { id: 'bife-de-chorizo-a-oswaldo-aranha', nome: 'Bife de Chorizo à Oswaldo Aranha',
          desc: 'Filet ao alho assado, batata portuguesa, farofa de ovos e molho à campanha', preco: 79 },
        { id: 'filet-da-nessa', nome: 'Filet da Nessa',
          desc: 'Medalhões de mignon com creme de brie e shitake, talharim artesanal ao alho e óleo', preco: 84 },
        { id: 'filet-a-francesa', nome: 'Filet à Francesa', preco: 79 },
      ],
    }],
  },

  {
    id: 'entradas-e-petiscos',
    nome: 'Entradas e Petiscos',
    grupos: [{
      itens: [
        { id: 'linguica-recheada-com-queijo-coalho', nome: 'Linguiça Recheada com Queijo Coalho',
          desc: 'Acompanha pão de alho e molho chimichurri', preco: 42 },
        { id: 'fish-and-chips', nome: 'Fish and Chips',
          desc: 'Clássico peixe crocante com batata rústica, acompanha molho tártaro', preco: 42 },
        { id: 'rock-fries', nome: 'Rock Fries',
          desc: 'Batata frita com cheddar e crocks de bacon', preco: 39 },
        { id: 'german-balls', nome: 'German Balls',
          desc: 'Croquete de carne estilo alemão, acompanha mostarda escura', preco: 39 },
        { id: 'cheese-nugget', nome: 'Cheese Nugget',
          desc: 'Nuggets caseiros recheados com American Cheese, acompanha molho mostarda e mel', preco: 36 },
        { id: 'linguica-pernil', nome: 'Linguiça Pernil',
          desc: 'Acompanha farofa e chimichurri', preco: 25 },
        { id: 'pao-de-alho', nome: 'Pão de Alho', nota: 'Unidade', preco: 12 },
        { id: 'shrimp-garlic-bread', nome: 'Shrimp Garlic Bread',
          desc: 'Pão de alho com camarões grelhados, catupiry e mussarela maçaricada', preco: 39 },
        { id: 'provolone-sticks', nome: 'Provolone Sticks',
          desc: 'Acompanha molho pomodoro rústico artesanal', preco: 42 },
        { id: 'pasteis-de-brie-com-geleia-de-damasco', nome: 'Pastéis de Brie com Geleia de Damasco', preco: 42 },
        { id: 'pasteis-de-camarao', nome: 'Pastéis de Camarão', nota: '4 unidades', preco: 39 },
        { id: 'pasteis-de-bacalhau', nome: 'Pastéis de Bacalhau', nota: '4 unidades', preco: 40 },
        { id: 'pasteis', nome: 'Pastéis', nota: '6 unidades',
          desc: 'Carne, Queijo ou Palmito', preco: 39 },
        { id: 'kafta', nome: 'Kafta',
          desc: 'Acompanha farofa tradicional e chimichurri', preco: 25 },
        { id: 'carpaccio', nome: 'Carpaccio',
          desc: 'Com molho de alcaparras, maionese da casa, rúcula e fatias de baguete com alecrim', preco: 42 },
        { id: 'cod-fish-balls', nome: 'Cod Fish Balls',
          desc: 'Bolinho de bacalhau', preco: 39 },
        { id: 'aipim-com-torresmo', nome: 'Aipim com Torresmo', preco: 50 },
      ],
    }],
  },

  {
    id: 'carnes',
    nome: 'Carnes',
    grupos: [
      {
        itens: [
          { id: 'lomo-relleno', nome: 'Lomo Relleno',
            desc: '2 steaks de mignon recheado com presunto de parma e queijo emental', preco: 85 },
          { id: 'baby-beef-cheese', nome: 'Baby Beef Cheese', nota: 'Para 2 pessoas',
            desc: 'Baby Beef 750g com muzzarella maçaricada e chimichurri', preco: 129 },
          { id: 'picanha-uruguaia', nome: 'Picanha Uruguaia',
            desc: 'Steak de picanha, acompanha molho chimichurri', preco: 79 },
          { id: 'milanesa-napolitana', nome: 'Milanesa Napolitana',
            desc: 'Baby Beef com muzzarella de búfala e molho de tomate', preco: 69 },
          { id: 'pork-ribs', nome: 'Pork Ribs', nota: 'Para 2 pessoas',
            desc: 'Costelinha suína com molho barbecue e salada coleslaw', preco: 99 },
          { id: 'fraldinha-red', nome: 'Fraldinha Red',
            desc: 'Corte totalmente limpo e sem gordura, preparado na manteiga de alho', preco: 59 },
          { id: 'prime-rib-angus', nome: 'Prime Rib Angus',
            desc: 'Corte nobre da linha angus, é o filé da costela com osso, muito macio e suculento, acompanha molho chimichurri',
            precos: [{ rotulo: 'Média 600g', valor: 129 }, { rotulo: 'Média 1kg', valor: 189 }] },
          { id: 'ny-stripe-black-angus', nome: 'NY Stripe / Black Angus',
            desc: 'Corte muito saboroso e macio, acompanha molho chimichurri', preco: 79 },
          { id: 'steak-and-shrimp', nome: 'Steak and Shrimp',
            desc: 'Medalhão de mignon com camarões ao alho, salada coleslaw e manteiga de ervas', preco: 99 },
          { id: 'file-mignon-grelhado', nome: 'Filé Mignon Grelhado', preco: 69 },
          { id: 'salmao-grelhado', nome: 'Salmão Grelhado', preco: 79 },
          { id: 'frango-grelhado', nome: 'Frango Grelhado', preco: 46 },
        ],
      },
      {
        nome: 'Sugestões para 2 pessoas',
        itens: [
          { id: 'picanha-uruguaia-2', midia: 'picanha-uruguaia', nome: 'Picanha Uruguaia',
            desc: 'Steak de picanha, acompanha molho chimichurri, arroz branco, farofa de bacon e batata frita', preco: 152 },
          { id: 'ny-stripe-black-angus-2', midia: 'ny-stripe-black-angus', nome: 'NY Stripe / Black Angus',
            desc: 'Corte muito saboroso e macio, acompanha molho chimichurri, arroz branco, farofa de bacon e mandioquinha frita', preco: 149 },
        ],
      },
    ],
  },

  {
    id: 'acompanhamentos',
    nome: 'Acompanhamentos',
    grupos: [{
      itens: [
        { id: 'aipim', nome: 'Aipim', desc: 'Na manteiga de garrafa', preco: 36 },
        { id: 'pure-de-baroa-com-gorgonzola', nome: 'Purê de Baroa com Gorgonzola', preco: 36 },
        { id: 'arroz-com-brocolis-e-alho-torrado', nome: 'Arroz com Brócolis e Alho Torrado', preco: 29 },
        { id: 'arroz-branco', nome: 'Arroz Branco', preco: 15 },
        { id: 'arroz-com-fraldinha', nome: 'Arroz com Fraldinha',
          desc: 'Arroz soltinho preparado com fraldinha macia e finalizado com tempero verde fresco', preco: 40 },
        { id: 'wine-rice', nome: 'Wine Rice',
          desc: 'Cozido no vinho, com presunto, mussarela, ovo e alho poró', preco: 39 },
        { id: 'batata-rustica', nome: 'Batata Rústica', desc: 'Com alecrim', preco: 29 },
        { id: 'garlic-mashed-potato', nome: 'Garlic Mashed Potato',
          desc: 'Clássico purê de batatas com alho', preco: 25 },
        { id: 'arroz-a-piamontese', nome: 'Arroz à Piamontese',
          desc: 'Com queijo Grana Padano e cogumelos frescos', preco: 42 },
        { id: 'mac-n-cheese', nome: "Mac'n Cheese", desc: 'Com bacon crispy em cubos', preco: 29 },
        { id: 'mix-de-folhas', nome: 'Mix de Folhas', desc: 'Acompanha molho da casa', preco: 29 },
        { id: 'vinagrete-tradicional', nome: 'Vinagrete Tradicional', preco: 15 },
        { id: 'vinagrete-cogumelos', nome: 'Vinagrete', desc: 'Com mix de cogumelos', preco: 25 },
        { id: 'tabua-de-legumes', nome: 'Tábua de Legumes', preco: 32 },
        { id: 'farofa-de-ovos', nome: 'Farofa de Ovos', preco: 25 },
        { id: 'farofa-de-banana', nome: 'Farofa de Banana', desc: 'Com banana da terra', preco: 25 },
        { id: 'farofa-de-bacon', nome: 'Farofa de Bacon',
          desc: 'Com linguiça artesanal, cebola e couve', preco: 25 },
        { id: 'fries', nome: 'Fries', preco: 29 },
      ],
    }],
  },

  {
    id: 'saladas',
    nome: 'Saladas',
    grupos: [{
      itens: [
        { id: 'mix-de-folhas-com-salmao-defumado', nome: 'Mix de Folhas com Salmão Defumado', preco: 49 },
        { id: 'ceasar-com-frango', nome: 'Ceasar com Frango',
          desc: 'Preparada com alface, molho ceasar, frango grelhado, croutons e queijo ralado', preco: 42 },
        { id: 'ceasar-com-camarao', nome: 'Ceasar com Camarão',
          desc: 'Preparada com alface, molho ceasar, camarões grelhados, croutons e queijo ralado', preco: 49 },
      ],
    }],
  },

  {
    id: 'sea-food',
    nome: 'Sea Food',
    grupos: [{
      itens: [
        { id: 'bistro-shrimp-pasta', nome: 'Bistrô Shrimp Pasta',
          desc: 'Talharim caseiro, camarões, cogumelos, tomate, rúcula e manjericão', preco: 79 },
        { id: 'moqueca-de-linguado', nome: 'Moqueca de Linguado',
          desc: 'Moqueca clássica de Linguado em um molho aromático, rico em sabores, especiarias e leite de coco com arroz branco e farofa de dendê',
          precos: [{ rotulo: 'Para 1 pessoa', valor: 90 }, { rotulo: 'Para 2 pessoas', valor: 170 }] },
        { id: 'moqueca-vegana', nome: 'Moqueca Vegana',
          desc: 'Moqueca de banana da terra com molho aromático, rico em sabores, especiarias e leite de coco, acompanha arroz branco e farofa de dendê',
          precos: [{ rotulo: 'Para 1 pessoa', valor: 79 }, { rotulo: 'Para 2 pessoas', valor: 140 }] },
        { id: 'ceviche', nome: 'Ceviche',
          desc: 'Peixe branco e salmão marinado, acompanha chips de batata doce', preco: 59 },
        { id: 'fish-fillet', nome: 'Fish Fillet',
          desc: 'Filet de pescado (linguado ou cherne) com purê de banana da terra, palmito, brócolis e tomate grape', preco: 79 },
      ],
    }],
  },

  {
    id: 'brew-burgers',
    nome: 'Brew Burgers',
    capa: 'brew-burgers',
    grupos: [{
      itens: [
        { id: 'classic-rock-burger', nome: 'Classic Rock Burger',
          desc: '200g blend da casa com queijo emental, cebola roxa, alface americana e tomate no pão brioche', preco: 48 },
        { id: 'chicken-burger', nome: 'Chicken Burger',
          desc: '150g de blend de frango, alface americana, cebola roxa e molho especial da casa no pão de brioche', preco: 39 },
        { id: 'salmon-burger', nome: 'Salmon Burger',
          desc: '100g de blend de salmão fresco, alface americana, cebola roxa e molho especial da casa no pão brioche', preco: 48 },
        { id: 'rush-bacon-burger', nome: 'Rush Bacon Burger',
          desc: '200g blend da casa, dobro de american cheese, bacon crispy em fatias, bacon em cubos e maionese de bacon no pão de brioche', preco: 48 },
        { id: 'garlic-onion-smash-burger', nome: 'Garlic Onion Smash Burger',
          desc: '2 smash burgers de 100g blend da casa cada, dobro de american cheese, pasta de alho e cebola no azeite, no pão de brioche', preco: 46 },
        { id: 'italy-smash-burger', nome: 'Italy Smash Burger',
          desc: '2 smash burgers de 100g blend da casa cada, dobro de mussarela de búfala, molho pomodoro rústico e rúcula no pão de brioche', preco: 49 },
        { id: 'double-cheese-smash-burger', nome: 'Double Cheese Smash Burger',
          desc: '2 smash burgers de 100g blend da casa cada, dobro de american cheese e molho especial da casa no pão de brioche', preco: 46 },
        { id: 'back-in-black-burger', nome: 'Back in Black Burger',
          desc: '200g blend da casa com cebola caramelizada, bacon e queijo cheddar no pão australiano', preco: 48 },
        { id: 'honey-salad-burger', nome: 'Honey Salad Burger',
          desc: '200g blend da casa, american cheese, alface americana, picles de pepino, molho mostarda e mel, no pão australiano', preco: 48 },
      ],
    }],
  },

  {
    id: 'baguetes',
    nome: 'Baguetes',
    grupos: [{
      itens: [
        { id: 'baguete-parmesao-mignon', nome: 'Baguete Parmesão Mignon',
          desc: 'Baguete de parmesão com mignon, cebola roxa, queijo maçaricado e pasta de alho', preco: 48 },
        { id: 'baguete-parmesao-mix-cogumelo', nome: 'Baguete Parmesão Mix Cogumelo',
          desc: 'Baguete de parmesão com mix de cogumelos ao shoyo, cebola roxa, queijo maçaricado e pasta de alho', preco: 48 },
        { id: 'baguete-roast-beef-bbq', nome: 'Baguete Roast Beef BBQ',
          desc: 'Baguete de parmesão com roast beef, alface americana, cebola roxa, tomate e molho BBQ', preco: 48 },
      ],
    }],
  },

  {
    id: 'sobremesas',
    nome: 'Sobremesas',
    grupos: [{
      itens: [
        { id: 'o-melhor-marshmallow-do-mundo', nome: 'O Melhor Marshmallow do Mundo',
          desc: 'Com morangos', preco: 28 },
        { id: 'panqueca-dulce-de-leche', nome: 'Panqueca Dulce de Leche',
          desc: 'Panqueca com tradicional doce de leite argentino, açúcar maçaricado e flor de sal', preco: 36 },
        { id: 'brigadeiro-de-colher', nome: 'Brigadeiro de Colher',
          desc: 'Com morango fatiado e farofa de paçoca', preco: 28 },
        { id: 'cocada-cremosa-na-cumbuca', nome: 'Cocada Cremosa na Cumbuca',
          desc: 'Com sorvete de creme artesanal', preco: 28 },
        { id: 'sorvete-da-casa', nome: 'Sorvete da Casa',
          desc: 'Creme, chocolate, Grana Padano com goiabada, limão siciliano', preco: 16 },
      ],
    }],
  },

  {
    id: 'drinks',
    nome: 'Drinks',
    capa: 'drinks',
    grupos: [
      {
        nome: 'Gin Tônica',
        precos: [{ rotulo: "Gordon's", valor: 34 }, { rotulo: 'Tanqueray', valor: 36 }],
        itens: [
          { id: 'the-trees', nome: 'The Trees', desc: 'Gin, tônica, Monin de menta, alecrim, zimbro e limão siciliano' },
          { id: 'la-villa-strangiato', nome: 'La Villa Strangiato', desc: 'Gin, tônica, Monin de maracujá, hortelã, gengibre, laranja e maracujá' },
          { id: 'red-barchetta', nome: 'Red Barchetta', desc: 'Gin, tônica, Monin de morango, hibisco, pimenta seca e morango' },
          { id: 'feeling-good', nome: 'Feeling Good', desc: 'Gin, tônica, Monin de limão siciliano, cravo, canela e limão siciliano' },
          { id: 'watermelon-sugar', nome: 'Watermelon Sugar', desc: 'Gin, tônica, Monin de melancia, limão, hortelã e gelo de melancia' },
          { id: 'tnt', nome: 'TNT', desc: 'Gin, tônica, Monin de toranja, hortelã, anis estrelado e tangerina' },
          { id: 'simple-man', nome: 'Simple Man', desc: 'Gin, limão, laranja e tônica' },
        ],
      },
      {
        nome: 'Caipirinha & Mojito',
        itens: [
          { id: 'caipirinha', nome: 'Caipirinha',
            precos: [{ rotulo: 'Cachaça', valor: 26 }, { rotulo: 'Smirnoff', valor: 34 }, { rotulo: 'Absolut', valor: 36 }],
            sabores: ['Limão', 'Lima', 'Maracujá', 'Morango', 'Abacaxi', '3 Limões', 'Maracujá c/ Gengibre', 'Tangerina c/ Hortelã'] },
          { id: 'mojito', nome: 'Mojito', desc: 'Rum, hortelã e soda', preco: 30,
            sabores: ['Limão', 'Maracujá', 'Morango'] },
        ],
      },
      {
        nome: 'Coquetéis',
        itens: [
          { id: 'aperol-spritz', nome: 'Aperol Spritz', desc: 'Aperol, Cointreau, espumante e soda', preco: 36 },
          { id: 'clericot', nome: 'Clericot', desc: 'Espumante, Triple Sec, soda e frutas', preco: 38 },
          { id: 'alexander', nome: 'Alexander', desc: 'Conhaque, licor de chocolate, leite condensado e canela em pó', preco: 34 },
          { id: 'pina-colada', nome: 'Piña Colada', desc: 'Rum, abacaxi, leite de coco, creme de leite e leite condensado', preco: 30 },
          { id: 'margarita', nome: 'Margarita', desc: 'Tequila, Cointreau', preco: 32, sabores: ['Limão', 'Tangerina', 'Morango'] },
          { id: 'moscow-mule', nome: 'Moscow Mule', desc: 'Vodka, xarope de gengibre, citrus e espuma de gengibre', preco: 35 },
          { id: 'whisky-sour', nome: 'Whisky Sour', desc: 'Bourbon, suco de limão e açúcar', preco: 40 },
          { id: 'dry-martini', nome: 'Dry Martini', desc: 'Gin, vermute seco e azeitona', preco: 30 },
          { id: 'negroni', nome: 'Negroni', desc: 'Gin, Campari, vermute vermelho e laranja', preco: 36 },
          { id: 'sex-on-the-beach', nome: 'Sex on the Beach', desc: 'Vodka, suco de laranja e Monin de pêssego', preco: 30 },
          { id: 'explosive', nome: 'Explosive', desc: 'Bourbon blend (Daniels e Honey), maracujá, pimenta rosa e canela em pau', preco: 38 },
          { id: 'coquetel-de-frutas', nome: 'Coquetel de Frutas', nota: 'Sem álcool',
            desc: 'Morango, suco de abacaxi, suco de goiaba, suco de maracujá, leite condensado, creme de leite e grenadine', preco: 30 },
        ],
      },
    ],
  },

  {
    id: 'bebidas',
    nome: 'Bebidas',
    compacta: true,
    grupos: [
      { nome: 'Long Neck', itens: [
        { id: 'heineken-zero-ln', nome: 'Heineken Zero', preco: 12.9 },
        { id: 'heineken-ln', nome: 'Heineken', preco: 12.9 },
        { id: 'stella-artois-ln', nome: 'Stella Artois', preco: 12.9 },
        { id: 'corona-ln', nome: 'Corona', preco: 12.9 },
        { id: 'corona-zero-ln', nome: 'Corona Zero', preco: 12.9 },
        { id: 'eisenbahn-ipa-ln', nome: 'Eisenbahn IPA', preco: 12.9 },
        { id: 'praya-ln', nome: 'Praya', preco: 12.9 },
        { id: 'lagunitas-ipa-ln', nome: 'Lagunitas IPA', preco: 12.9 },
      ] },
      { nome: 'Long Neck', nota: 'Sem glúten', itens: [
        { id: 'stella-pure-gold-ln', nome: 'Stella Artois Pure Gold', preco: 12.9 },
        { id: 'amstel-ultra-ln', nome: 'Amstel Ultra', preco: 12.9 },
        { id: 'praya-sg-ln', nome: 'Praya', preco: 12.9 },
      ] },
      { nome: 'Garrafa', nota: '600ml', itens: [
        { id: 'heineken-600', nome: 'Heineken', preco: 19 },
        { id: 'antarctica-original-600', nome: 'Antarctica Original', preco: 17.5 },
        { id: 'spaten-600', nome: 'Spaten', preco: 17.5 },
        { id: 'corona-600', nome: 'Corona', preco: 17.5 },
        { id: 'stella-artois-600', nome: 'Stella Artois', preco: 17.5 },
        { id: 'baden-baden-600', nome: 'Baden Baden', preco: 25 },
      ] },
      { nome: 'Chopp', nota: '300ml', itens: [
        { id: 'chopp-heineken', nome: 'Heineken', preco: 14.9 },
        { id: 'chopp-brahma', nome: 'Brahma', preco: 12.9 },
        { id: 'chopp-hanz-ipa', nome: 'Hanz IPA', preco: 19 },
      ] },
      { nome: 'Energético', itens: [
        { id: 'red-bull', nome: 'Red Bull', nota: 'Sabores', preco: 20 },
      ] },
      { nome: 'Sem álcool', itens: [
        { id: 'coca-cola', nome: 'Coca-Cola', preco: 8.5 },
        { id: 'coca-cola-zero', nome: 'Coca-Cola Zero', preco: 8.5 },
        { id: 'guarana', nome: 'Guaraná', preco: 8.5 },
        { id: 'guarana-zero', nome: 'Guaraná Zero', preco: 8.5 },
        { id: 'sprite', nome: 'Sprite', preco: 8.5 },
        { id: 'tonica-antarctica', nome: 'Tônica Antarctica', preco: 8.5 },
        { id: 'tonica-schweppes', nome: 'Tônica Schweppes', preco: 8.5 },
        { id: 'tonica-zero', nome: 'Tônica Zero', preco: 8.5 },
        { id: 'h2o', nome: 'H2O', preco: 8.5 },
        { id: 'fys', nome: 'Fys', preco: 7.5 },
        { id: 'mate-leao', nome: 'Mate Leão', preco: 8 },
        { id: 'guaravita', nome: 'Guaravita', preco: 5 },
        { id: 'ice-tea', nome: 'Ice Tea', preco: 8 },
        { id: 'agua', nome: 'Água', preco: 7.9 },
        { id: 'agua-com-gas', nome: 'Água com Gás', preco: 7.9 },
        { id: 'suco-del-valle', nome: 'Suco Del Valle', preco: 8.5 },
      ] },
    ],
  },

  // Carta de vinhos — conteúdo da página https://j8v9slc8.mule.page/ (set/2026).
  // `vinhos: true` → cada item vira uma linha com a miniatura da garrafa.
  {
    id: 'adega-brew',
    nome: 'Adega Brew',
    vinhos: true,
    grupos: [
      { nome: 'Espumantes', nota: 'Brasil · Serra Gaúcha', itens: [
        { id: 'casa-perini-brut', nome: 'Casa Perini Brut', pais: 'BR', preco: 110,
          detalhes: { uvas: 'Chardonnay & Pinot Noir', pais: 'Brasil', regiao: 'Serra Gaúcha', teor: '11,8%' },
          desc: 'Espumante fresco, elegante e equilibrado.' },
        { id: 'casa-perini-rose', nome: 'Casa Perini Rosé', pais: 'BR', preco: 110,
          detalhes: { uvas: 'Chardonnay & Pinot Noir', pais: 'Brasil', regiao: 'Serra Gaúcha', teor: '11,8%' },
          desc: 'Leve, delicado e com notas de frutas vermelhas.' },
        { id: 'salton-brut', nome: 'Salton Brut', pais: 'BR', preco: 110,
          detalhes: { uvas: 'Chardonnay & Riesling', pais: 'Brasil', regiao: 'Serra Gaúcha', teor: '11,5%' },
          desc: 'Refrescante, com boa acidez e perlage fina.' },
      ] },
      { nome: 'Vinhos Brancos', nota: 'Refrescantes & aromáticos', itens: [
        { id: 'benjamin-chardonnay', nome: 'Benjamin Chardonnay', pais: 'AR', preco: 95,
          detalhes: { uvas: 'Chardonnay', pais: 'Argentina', regiao: 'Mendoza', teor: '13%' },
          desc: 'Branco fresco com notas de frutas tropicais.' },
        { id: 'intimista-branco', nome: 'Intimista Branco', pais: 'PT', preco: 65,
          detalhes: { uvas: 'Antão Vaz, Arinto & Roupeiro', pais: 'Portugal', regiao: 'Alentejo', teor: '12,5%' },
          desc: 'Leve e aromático, muito agradável.' },
        { id: 'cosecha-tarapaca-chardonnay', nome: 'Cosecha Tarapacá Chardonnay', pais: 'CL', preco: 65,
          detalhes: { uvas: 'Chardonnay', pais: 'Chile', regiao: 'Vale Central', teor: '13%' },
          desc: 'Frutado e refrescante.' },
        { id: 'la-vache-branco', nome: 'La Vache Branco', pais: 'FR', preco: 75,
          detalhes: { uvas: 'Sauvignon Blanc & Colombard', pais: 'França', regiao: 'Languedoc', teor: '12%' },
          desc: 'Leve, fresco e equilibrado.' },
        { id: 'casa-viva-sauvignon-blanc', nome: 'Casa Viva Sauvignon Blanc', pais: 'CL', preco: 165,
          detalhes: { uvas: 'Sauvignon Blanc', pais: 'Chile', regiao: 'Vale de Casablanca', teor: '13%' },
          desc: 'Aromático, cítrico e refrescante.' },
      ] },
      { nome: 'Tintos', nota: 'Argentina', itens: [
        { id: 'benjamin-malbec', nome: 'Benjamin Malbec', pais: 'AR', preco: 95,
          detalhes: { uvas: 'Malbec', pais: 'Argentina', regiao: 'Mendoza', teor: '13%' },
          desc: 'Malbec macio com notas de ameixa.' },
        { id: 'trivento-reserve-cabernet-malbec', nome: 'Trivento Reserve Cabernet · Malbec', pais: 'AR', preco: 120,
          detalhes: { uvas: 'Cabernet Sauvignon & Malbec', pais: 'Argentina', regiao: 'Mendoza', teor: '13%' },
          desc: 'Combina a estrutura e a elegância da Cabernet Sauvignon com a exuberância frutada e os taninos aveludados da Malbec, resultando em um vinho equilibrado e macio.' },
        { id: 'altos-del-plata-malbec', nome: 'Altos Del Plata Malbec', pais: 'AR', preco: 145,
          detalhes: { uvas: 'Malbec', pais: 'Argentina', regiao: 'Mendoza', teor: '13,5%' },
          desc: 'Vinho jovem e frutado, ideal para o dia a dia e para acompanhar carnes grelhadas.' },
        { id: 'terrazas-de-los-andes-reserva-malbec', nome: 'Terrazas de los Andes Reserva Malbec', pais: 'AR', preco: 220,
          detalhes: { uvas: 'Malbec', pais: 'Argentina', regiao: 'Mendoza', teor: '14%' },
          desc: 'Reconhecido internacionalmente por sua excelente relação custo-benefício, destaca-se pelo frescor, notas intensas de frutas vermelhas e negras.' },
      ] },
      { nome: 'Tintos', nota: 'Chile', itens: [
        { id: 'santa-alba-malbec', nome: 'Santa Alba Malbec', pais: 'CL', preco: 99,
          detalhes: { uvas: 'Malbec', pais: 'Chile', regiao: 'Vale Central', teor: '13%' },
          desc: 'Frutado e equilibrado.' },
        { id: 'santa-alba-carmenere', nome: 'Santa Alba Carménère', pais: 'CL', preco: 99,
          detalhes: { uvas: 'Carménère', pais: 'Chile', regiao: 'Vale Central', teor: '13%' },
          desc: 'Frutas negras e toque de especiarias.' },
        { id: 'santa-alba-cabernet-sauvignon', nome: 'Santa Alba Cabernet Sauvignon', pais: 'CL', preco: 99,
          detalhes: { uvas: 'Cabernet Sauvignon', pais: 'Chile', regiao: 'Vale Central', teor: '13%' },
          desc: 'Cabernet jovem e versátil.' },
        { id: 'casa-viva-cabernet-sauvignon', nome: 'Casa Viva Cabernet Sauvignon', pais: 'CL', preco: 105,
          detalhes: { uvas: 'Cabernet Sauvignon', pais: 'Chile', regiao: 'Vale de Casablanca', teor: '13,5%' },
          desc: 'Estruturado e elegante.' },
        { id: 'casa-viva-gran-reserva', nome: 'Casa Viva Gran Reserva Cabernet Sauvignon', pais: 'CL', preco: 185,
          detalhes: { uvas: 'Cabernet Sauvignon', pais: 'Chile', regiao: 'Vale de Casablanca', teor: '14%' },
          desc: 'Complexo e com passagem por barrica.' },
        { id: 'viejo-feo-cabernet-sauvignon', nome: 'Viejo Feo Cabernet Sauvignon', pais: 'CL', preco: 130,
          detalhes: { uvas: 'Cabernet Sauvignon', pais: 'Chile', regiao: 'Vale Central', teor: '13,5%' },
          desc: 'Intenso, com frutas negras maduras.' },
        { id: 'cosecha-tarapaca-carmenere', nome: 'Cosecha Tarapacá Carménère', pais: 'CL', preco: 75,
          detalhes: { uvas: 'Carménère', pais: 'Chile', regiao: 'Vale Central', teor: '12,5%' },
          desc: 'Taninos doces e equilibrados, com notas de frutas vermelhas e especiarias.' },
      ] },
      { nome: 'Tintos', nota: 'França', itens: [
        { id: 'cave-de-ladac-cabernet-sauvignon', nome: 'Cave de Ladac Cabernet Sauvignon', pais: 'FR', preco: 142,
          detalhes: { uvas: 'Cabernet Sauvignon', pais: 'França', regiao: 'Languedoc-Roussillon', teor: '13%' },
          desc: 'Elegante e equilibrado.' },
      ] },
      { nome: 'Tintos', nota: 'Portugal', itens: [
        { id: 'julia-florista', nome: 'Julia Florista', pais: 'PT', preco: 91,
          detalhes: { uvas: 'Castelão, Tinta Roriz & Touriga Nacional', pais: 'Portugal', regiao: 'Lisboa', teor: '13,5%' },
          desc: 'Macio, frutado e agradável.' },
        { id: 'intimista-tinto', nome: 'Intimista Tinto', pais: 'PT', preco: 65,
          detalhes: { uvas: 'Aragonez & Trincadeira', pais: 'Portugal', regiao: 'Alentejo', teor: '13,5%' },
          desc: 'Frutas maduras e taninos suaves.' },
        { id: 'porta-6', nome: 'Porta 6', pais: 'PT', preco: 98,
          detalhes: { uvas: 'Aragonez, Castelão & Touriga Nacional', pais: 'Portugal', regiao: 'Lisboa', teor: '13,5%' },
          desc: 'Jovem, macio e fácil de beber.' },
        { id: 'da-pipa-colheita', nome: 'Da Pipa Colheita', pais: 'PT', preco: 85,
          detalhes: { uvas: 'Castelão & Tinta Roriz', pais: 'Portugal', regiao: 'Lisboa', teor: '13%' },
          desc: 'Leve e frutado.' },
        { id: 'pinta-negra', nome: 'Pinta Negra', pais: 'PT', preco: 135,
          detalhes: { uvas: 'Castelão, Touriga Nacional & Syrah', pais: 'Portugal', regiao: 'Lisboa', teor: '13,5%' },
          desc: 'Estruturado e persistente.' },
        { id: 'vale-de-escadas-reserva', nome: 'Vale de Escadas Reserva', pais: 'PT', preco: 180,
          detalhes: { uvas: 'Touriga Nacional, Touriga Franca & Tinta Roriz', pais: 'Portugal', regiao: 'Douro', teor: '14%' },
          desc: 'Elegante, intenso e complexo.' },
      ] },
      { nome: 'Tintos', nota: 'Espanha', itens: [
        { id: 'pata-negra-tempranillo', nome: 'Pata Negra Tempranillo', pais: 'ES', preco: 99,
          detalhes: { uvas: 'Tempranillo', pais: 'Espanha', regiao: 'Valdepeñas', teor: '13%' },
          desc: 'Tempranillo macio e equilibrado.' },
        { id: 'torcida-crianza', nome: 'Torcida Crianza', pais: 'ES', preco: 195,
          detalhes: { uvas: 'Tempranillo', pais: 'Espanha', regiao: 'Rioja', teor: '14%' },
          desc: 'Complexo, com notas de carvalho.' },
      ] },
      { nome: 'Taça de vinho', itens: [
        { id: 'taca-de-vinho', nome: 'Taça de vinho', preco: 28 },
      ] },
    ],
  },
];
